import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import WagmiContextProvider from "@/lib/providers/wagmi-provider";
import { ThemeProvider } from "@/lib/providers/nexttheme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Derivative Vault",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiContextProvider cookies={cookies}>  
          <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem={false}
               disableTransitionOnChange
             >
               {children}
             </ThemeProvider>
        </WagmiContextProvider>
      </body>
    </html>
  );
}
