export const derivativeVaultContractAbi = [
  {
    inputs: [
      { internalType: "address", name: "_liquidityManager", type: "address" },
      { internalType: "address", name: "_rateOracle", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "derivativeToken",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "collateralAsset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exercisePrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiryTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isBuyOption",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "issueAmount",
        type: "uint256",
      },
    ],
    name: "OptionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "derivativeToken",
        type: "address",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "earnings",
        type: "uint256",
      },
    ],
    name: "OptionExercised",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newOracle",
        type: "address",
      },
    ],
    name: "OracleUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "derivativeToken", type: "address" },
    ],
    name: "cleanupExpiredOptions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "derivativeRecords",
    outputs: [
      { internalType: "address", name: "derivativeToken", type: "address" },
      { internalType: "address", name: "collateralAsset", type: "address" },
      { internalType: "uint256", name: "exercisePrice", type: "uint256" },
      { internalType: "uint256", name: "expiryTime", type: "uint256" },
      { internalType: "bool", name: "isBuyOption", type: "bool" },
      { internalType: "bool", name: "exercised", type: "bool" },
      { internalType: "uint256", name: "collateralAmount", type: "uint256" },
      { internalType: "address", name: "poolAddress", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "exerciseOption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "collateralAsset", type: "address" },
      { internalType: "uint256", name: "exercisePrice", type: "uint256" },
      { internalType: "uint256", name: "expiryTime", type: "uint256" },
      { internalType: "bool", name: "isBuyOption", type: "bool" },
      { internalType: "uint256", name: "issueAmount", type: "uint256" },
      { internalType: "address", name: "poolAddress", type: "address" },
    ],
    name: "generateOptions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserDerivativeToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserExercises",
    outputs: [
      {
        components: [
          { internalType: "address", name: "derivativeToken", type: "address" },
          { internalType: "address", name: "collateralAsset", type: "address" },
          { internalType: "uint256", name: "exercisePrice", type: "uint256" },
          { internalType: "uint256", name: "expiryTime", type: "uint256" },
          { internalType: "bool", name: "isBuyOption", type: "bool" },
          { internalType: "bool", name: "exercised", type: "bool" },
          {
            internalType: "uint256",
            name: "collateralAmount",
            type: "uint256",
          },
          { internalType: "address", name: "poolAddress", type: "address" },
        ],
        internalType: "struct DerivativeVault.DerivativeInfo[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "liquidityManager",
    outputs: [
      {
        internalType: "contract INonfungiblePositionManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rateOracle",
    outputs: [
      { internalType: "contract IRateOracle", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_rateOracle", type: "address" }],
    name: "updateOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userDerivativeTokens",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "validatedOracles",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
